const age = "38";
const firstName = "Wojtek";
console.log(firstName);
console.log(age);
console.log(`Nazywam się ${firstName} i mam ${age} lat`);
const header = document.querySelector(".page-header_heading--js");
console.log(header);
console.log(header.innerHTML);
header.innerHTML = `Nazywam się ${firstName} i mam ${age} lat`;
console.log(header.style);
header.style.color = "red";
